### PR TITLE
Feature/check dupe guess

### PR DESCRIPTION
**Pull request by bnonni**
**Done**
- adds function `no_duplicate_guess` to lib.rs to check the `fetched_guesses` against the `new_guess` submitted
- if the `fetched_guess` from DB has a null block or is equal to the `new_guess.block` and `fetched_guess.name` is equal to `new_guess.name` return `Err(fetched_guess.clone())`
- Else return `Ok(true)` that no dupes exist
- move fetching the target, block_path and guesses in front of posting new guess to API
- after fetching gueses, check for dupes; if no dupes, add new guess to DB, else fail with basic debug

**To Do**
- handle the dupe exists error with a frontend alert to the user
- need help on this task, unsure how to achieve this behavior

### CODE REVIEW

**Comment by notmandatory** [comment]
Rather than checking for duplicate guesses in the code this can be done via new DB constraints. See #10 .

**Comment by bnonni** [comment]
Closing in favor of #10

**Comment by bnonni** [comment]
@notmandatory I can't recall where we landed with this feature. Should I close this PR and adopt #10 making additional changes to handle displaying a front end error in the event the DB returns an error on the `UNIQUE` DB constraint?

**Comment by notmandatory** [comment]
Hey ya I'll this PR, I just merged #10 which does the basics of preventing dup nonces.

**Pull request closed without merging**
